[profile.default]
solc-version = "0.8.23"
#auto_detect_solc = false
cache = true
evm_version = 'london'
src = 'contracts'
test = 'src/test'
out = 'artifacts_forge'
libs = ["lib"]
remappings = [
  '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
  '@ds-test=lib/ds-test/src/',
  '@std=lib/forge-std/src/',
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
